# Generated by Django 5.0.5 on 2024-06-05 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='author_image/')),
                ('biography', models.CharField(max_length=1000)),
                ('nickname', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('book_cover', models.ImageField(upload_to='cover_book/')),
                ('description', models.CharField(max_length=500)),
                ('number_pages', models.IntegerField()),
                ('format', models.CharField(choices=[('ebook', 'ebook'), ('physical', 'physical')], max_length=20)),
                ('publication_year', models.CharField(max_length=4)),
                ('volume', models.IntegerField()),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author_id', to='app.author')),
                ('genders', models.ManyToManyField(to='app.gender')),
            ],
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_image/')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookimage_book_id', to='app.book')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devoluption_date', models.DateField()),
                ('real_devoluption_date', models.DateField()),
                ('status', models.CharField(choices=[('returned', 'returned'), ('delayed', 'delayed'), ('borrowed', 'borrowed')], max_length=30)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookloan_book_id', to='app.book')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookloan_loan_id', to='app.loan')),
            ],
        ),
    ]
