# Generated by Django 5.0.5 on 2024-06-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='real_devoluption_date',
            field=models.DateField(null=True),
        ),
    ]
